---
title: "Renewable Energy: What factors explain the adoption of solar and wind power in EU countries?"
author: Camila & Tarun
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
---

Inputs {.sidebar}
---------------------------------

Traditional energy sources like coal, oil and natural gas, have contributed to high levels of pollution and greenhouse gas emissions worldwide.

One potential way of removing the impact of greenhouse gas emission is mitigation – that is, activities intended to reduce the magnitude of climate change and its impact on human life. 

The shift to cleaner forms of energy production through the adoption of renewable energy sources is a key mitigation strategy for countries like India and China. 

What about the European countries? Are they also switching to renewable energy? What factors explain the adoption of renewables - wind and solar - in European countries?


Column
---------------------------------

### What percentage of total electricity consumption in EU countries can be attributed to Renewable Energy? 

```{r, include=T, message=F, warning=FALSE, error=FALSE, echo=FALSE, type = 'html', results='asis', fig.height=4, cache=TRUE}

setwd("~/Desktop/CollaborativeDataMethods/VieiraKhanna_Assignment3/data_cleaning")

# Importing and cleaning data from Eurostat
source('Eurostat_and_Opec_data.R')

# Importing and cleaning data from World Bank
source('WDI_data.R')

# Merging the data
re_data <- merge(Combined_WDI,Combine_EuroStat,by = c("country", "year"), all.x = T, all.y = T)

# Remove missing values
re_data1 <- na.omit(re_data)

#creating var for solar and wind gen as percent of total elec consumption
re_data1$sw_pc_elec <- re_data1$re_gen/re_data1$elec_total*100 
re_data_map <- re_data1[which(re_data1$year == "2013"),]

library(googleVis)
# Plot
re_map <- gvisGeoChart(re_data_map, locationvar = 'country',
                      colorvar = 'sw_pc_elec',
                      options = list(
                        colors = "['#f7fcb9', '#31a354']",
                        region ="150"
                          ))
print(re_map, tag = 'chart')

```

### Solar and Wind Power Trends

```{r, include=T, message=F, warning=FALSE, error=FALSE, echo=FALSE}

re_data1$sw_rise <- unlist(
        tapply(re_data1$sw_pc_elec, re_data1$country, function(x) c(NA,100*diff(x)/x[-length(x)])))

library(reshape2)
library(plotly)

re_data2 <- re_data1[order(re_data1$year,re_data1$sw_rise),] #arranging data
countries10 <- tail(re_data2,10)[1] %>% as.matrix() %>% as.character() %>% paste(collapse = "|") #finding top10
uptake_changes <- filter(re_data2, grepl(countries10, country))


percent_change <- ggplot(data = uptake_changes,
       aes(x = year, y = sw_rise, group = country,colour = country)) +
    geom_line() +
    geom_point() +
        xlab(label = "\nYear") +
        ylab(label = "% change in RE uptake\n")

ggplotly(percent_change)

```


Column {data-width=500}
---------------------------------

### The impact of oil prices...

```{r, include=T, message=F, warning=FALSE, error=FALSE, echo=FALSE}

#re_data1$re_gen_sum <-aggregate(x = re_data1[c("re_gen")], FUN = sum, by = list(Group.date = re_data1$year))

library(plotly)
ay <- list(
  tickfont = list(color = "red"),
  overlaying = "y",
  side = "right",
  title = "Oil Prices")

plot_ly() %>%
  add_lines(x = "year", y = "re_gen_sum", name = "RE Generation(TWh)") %>%
  add_lines(x = "year", y = ~0:140, name = "Oil prices", yaxis = "y2") %>%
  layout(
   title = "RE generation VS. Oil Prices", yaxis2 = ay,
    xaxis = list(title="Year")
  )

```

